/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnotify_JavaBridge */

#ifndef _Included_jnotify_JavaBridge
#define _Included_jnotify_JavaBridge
#ifdef __cplusplus
extern "C" {
#endif
#undef jnotify_JavaBridge_TempEventTooCold
#define jnotify_JavaBridge_TempEventTooCold 0L
#undef jnotify_JavaBridge_TempEventTooHot
#define jnotify_JavaBridge_TempEventTooHot 1L
/*
 * Class:     jnotify_JavaBridge
 * Method:    startTemparatureSensorEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnotify_JavaBridge_startTemparatureSensorEngine
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class jnotify_JavaBridge_TemparatureEven */

#ifndef _Included_jnotify_JavaBridge_TemparatureEven
#define _Included_jnotify_JavaBridge_TemparatureEven
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
